# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20),
            preserve_default=False,
        ),
    ]
