# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_account', '0002_liability_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='estimatedbalance',
            new_name='balance',
        ),
    ]
