# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_account', '0003_auto_20160707_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
