# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_account', '0004_asset_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
