// Generated by CoffeeScript 1.10.0
(function() {
  var accounts;

  accounts = {
    capital: [
      {
        name: 'ANZ',
        currency: 'USD',
        openingbalance: 10.10,
        estimatedbalance: 10.10
      }, {
        name: 'ANZ',
        currency: 'USD',
        openingbalance: 10.10,
        estimatedbalance: 10.10
      }
    ]
  };

  window.AccountStore = function() {
    var self;
    riot.observable(this);
    if (JS_LOG_LEVEL < 2) {
      console.log('created AccountStore');
    }
    self = this;
    self.accounts = accounts;
    console.log(accounts);
    self.on('accounts_init', function() {
      if (JS_LOG_LEVEL < 2) {
        console.log('triggered accounts_init');
      }
      return self.trigger('accounts_changed', self.accounts);
    });
    return self.on('account_add', function(account, category) {
      self.accounts.category.push(account);
      return self.trigger('accounts_changed', accounts);
    });
  };

  window.accountstore = AccountStore();

  RiotControl.addStore(window.accountstore);

  RiotControl.trigger('accounts_changed');

}).call(this);
