// Generated by CoffeeScript 1.10.0
(function() {
  var appName, modelName;

  modelName = 'project';

  appName = 'projecttracker';

  window.TransactionStore = function() {
    var self;
    riot.observable(this);
    console.log('created TransactionStore');
    self = this;
    self.transactions = [];
    self.on('transactions_fetch', function() {
      var xhr;
      self.transactions = [
        {
          from_account: 'ANZ Bank',
          to_account: 'Mandiri',
          name: 'My transaction',
          description: 'Description',
          time: '2017-08-02 22:54',
          amt: '20.53'
        }, {
          from_account: 'ANZ Bank',
          to_account: 'Mandiri',
          name: 'My transaction',
          description: 'Description',
          time: '2017-08-02 22:54',
          amt: '20.53'
        }
      ];
      RiotControl.trigger('transactions_update');
      xhr = $.getJSON('/transactions');
      return xhr.done(function() {
        self.store.transactions = xhr.responseJSON;
        return RiotControl.trigger('transactions_update');
      });
    });
    self.on('transactions_init', function() {
      console.log('triggered transactions_init');
      return self.trigger('transactions_changed');
    });
    return self.on('transaction_add', function(transaction) {
      self.accounts.category.push(transaction);
      return self.trigger('transactions_changed', transaction);
    });
  };

}).call(this);

//# sourceMappingURL=TransactionStore.js.map
