// Generated by CoffeeScript 1.10.0
(function() {
  var appName, modelName;

  modelName = 'project';

  appName = 'projecttracker';

  window.TransactionStore = function(transactions) {
    riot.observable(this);
    this.transactions = transactions || [];
    this.edit = {};
    this.filters = '';

    /* Request the latest projects from DRF */
    this.on('transaction_list_load', function(opts) {
      var filters, page, per_page;
      opts = opts || {};
      page = opts.page || 1;
      per_page = opts.per_page || 100;
      filters = opts.filters || '';
      return self.filters = filters;
    });
    this.on('ping', function() {
      return alert('ping');
    });
    return this.on('tag_selected', function(e) {
      return console.log(e);
    });
  };

}).call(this);
